app_id: d47b7475-336b-42e0-802b-290e19b6f75d
app_secret: aiZOTIO459=];dxsbzRK71(
redirect: http://localhost:8000/tutorial/callback
scopes: openid profile offline_access user.read calendars.read
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token